stages:
    - build
    - test
    - bench
    - deploy

cache:
    paths:
        - .cache/conan/data

variables:
    FEDORA_RAWHIDE: "${CI_REGISTRY}/olena/pylene-dockers/fedora-rawhide"
    FEDORA_31: "${CI_REGISTRY}/olena/pylene-dockers/fedora-31"
    PACKAGE_NAME: "pylene" # Conan package name
    PACKAGE_TAG: "experimental" # Conan tag
    PACKAGE_VERSION: "head" # Version to build
    CMAKE_BUILD_PARALLEL_LEVEL: 6
    CONAN_USER: "lrde"

before_script:
        - conan config set storage.path="${CI_PROJECT_DIR}/.cache/conan/data"

########
# Test #
########

windows-debug:
    before_script:
        - conan config set storage.path="${env:CI_PROJECT_DIR}\.cache\conan\data"
        - Invoke-BatchFile -Path "${env:VCVAR2019}" -Parameters "${env:ARCH}"
    stage: build
    script:
        - mkdir build; cd build
        - conan install .. -s build_type=Debug --build missing
        - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=debug -D CMAKE_TOOLCHAIN_FILE="C:\vcpkg\scripts\buildsystems\vcpkg.cmake"
        - cmake --build . --target build-tests
        - ctest -L UnitTests --schedule-random --output-on-failure
    dependencies: []
    artifacts:
        reports:
            junit: [build/tests/UT*.xml, build/bench/tests/UT*.xml]
        expire_in: 15 days
    tags: [ windows ]
    when: manual
    variables:
        VCVAR2019: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat'
        ARCH: x64



.job-build-linux-base: &distcheck-linux-base
    stage: build
    script:
        - mkdir build && cd build
        - conan install .. -pr gcc-9 --build missing -e CXX=g++ -e CC=gcc
        - cmake -G Ninja .. -DCMAKE_BUILD_TYPE=$PYLENE_CONFIGURATION -DPYLENE_CODE_COVERAGE=OFF -DSANITIZE_ADDRESS=$ASAN -DSANITIZE_MEMORY=$MSAN -DSANITIZE_UNDEFINED=$UBSAN
        - cmake --build . --target Pylene
        - cmake --build . --target build-tests
        - ctest -L UnitTests --schedule-random --output-on-failure
    dependencies: []
    artifacts:
        reports:
            junit: [build/tests/UT*.xml, build/bench/tests/UT*.xml]
        expire_in: 15 days

.job-build-linux-coverage: &distcheck-linux-coverage
    stage: build
    script:
        - mkdir build && cd build
        - conan install .. -pr gcc-9 --build missing -e CXX=g++ -e CC=gcc
        - cmake -G Ninja .. -DCMAKE_BUILD_TYPE=$PYLENE_CONFIGURATION -DPYLENE_CODE_COVERAGE=ON -DGCOV_PATH=$COV -DSANITIZE_ADDRESS=$ASAN -DSANITIZE_MEMORY=$MSAN -DSANITIZE_UNDEFINED=$UBSAN
        - cmake --build . --target Pylene
        - cmake --build . --target build-tests
        - cmake --build . --target run-tests_coverage-gcovr-html
        - cmake --build . --target run-tests_coverage-lcov
        - lcov --list run-tests_coverage-lcov.info
    dependencies: []
    artifacts:
        paths:
            - build/run-tests_coverage-gcovr-html/
            - build/run-tests_coverage-lcov/
        reports:
            junit: [build/tests/UT*.xml, build/bench/tests/UT*.xml]
        expire_in: 15 days


# Msan not available for gcc. It requires instrumented libstdc++ and instrumented thirdparties so it is disabled for now.
# No tsan because no multithreaded code for now
# Asan, memsan and tsan are incompatible with each other within the same binary
# Asan and ubsan can work together


distcheck-linux-gcc9-release:
    <<: *distcheck-linux-base
    image: ${FEDORA_31}
    variables:
        PYLENE_CONFIGURATION: "Release"
        CXX: "g++"
        CC: "gcc"
        ASAN: "OFF"
        MSAN: "OFF"
        UBSAN: "OFF"

distcheck-linux-gcc9-debug-asan-ubsan:
    <<: *distcheck-linux-base
    image: ${FEDORA_31}
    variables:
        PYLENE_CONFIGURATION: "Debug"
        CXX: "g++"
        CC: "gcc"
        ASAN: "ON"
        MSAN: "OFF"
        UBSAN: "ON"


distcheck-linux-gcc9-debug-coverage:
    <<: *distcheck-linux-coverage
    image: ${FEDORA_31}
    variables:
        PYLENE_CONFIGURATION: "Debug"
        CXX: "g++"
        CC: "gcc"
        COV: "/usr/bin/gcov"
        ASAN: "OFF"
        MSAN: "OFF"
        UBSAN: "OFF"
    when: manual

#########
# Bench #
#########

.job-bench-linux-base: &distbench-linux-base
    stage: bench
    script:
        - mkdir build && cd build
        - conan install .. -pr gcc-9 --build missing -e CXX=g++ -e CC=gcc
        - cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . --target fetch-external-data
        - cmake --build . --target build-bench
        - cmake --build . --target run-all-benchmarks
        - ctest -L SpeedTests -V
    tags: [ "pylene-benchmarks" ]
    when: manual
    dependencies: []
    artifacts:
        name: "benchmark-results"
        paths:
            - build/bench/*.json
        expire_in: 15 days

distbench-linux-gcc9-release:
    <<: *distbench-linux-base
    image: ${FEDORA_31}
    variables:
        CXX: "g++"
        CC: "gcc"



#################
# Documentation #
#################

.documentation-base:  &documentation-base
    image: ${FEDORA_31}
    stage: build
    script:
        - mkdir build && cd build
        - conan install -u .. -pr gcc-9 --build missing -e CXX=g++ -e CC=gcc
        - cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . --target build-doc
        - mkdir ../public && mv doc/sphinx/* ../public/
    artifacts:
        name: "documentation"
        expire_in: 2 days
        paths:
            - public/

# Generate doc only
documentation:
    <<: *documentation-base
    except:
        - dev


##########
# Deploy #
##########

pages:
    <<: *documentation-base
    only:
        - dev

package:
    image: ${FEDORA_31}
    stage: deploy
    dependencies: []
    script:
        - mkdir build && cd build
        - conan user carlinet -r lrde-public -p $CONAN_LRDE_API_KEY
        - conan create .. $CONAN_USER/$PACKAGE_TAG --build missing -e CXX=g++ -e CC=gcc
        - conan upload -r lrde-public --all $PACKAGE_NAME/$PACKAGE_VERSION@$CONAN_USER/$PACKAGE_TAG
    only: [ "dev", "development/ranges", "development/cpp20" ]
