variables:
    CONAN_PRIVATE_REMOTE_NAME: "dutiona-lrde"                               # Conan remote name
    CONAN_PRIVATE_REMOTE_URL: "https://api.bintray.com/conan/dutiona/lrde"  # Conan remote name
    CONAN_USER: "dutiona"                                                   # Conan user name
    CONAN_API_KEY: "e2a665548385e82bf1ecbb4739d3582b83b8235f"

stages:
    - build
    - test
    - deploy

image: carlinet/buildimage


.job-build-linux-base: &distcheck-linux-base
    stage: test
    script:
        - mkdir build && cd build
        - conan remote add $CONAN_PRIVATE_REMOTE_NAME $CONAN_PRIVATE_REMOTE_URL
        - conan user
              -p $CONAN_API_KEY
              -r $CONAN_PRIVATE_REMOTE_NAME $CONAN_USER
        - conan remote list
        - conan install .. --build missing -o benchmark=$BENCHMARK
        - cmake ..
        - cmake --build . --config $PYLENE_CONFIGURATION --target check


distcheck-linux-gcc-release:
    <<: *distcheck-linux-base
    variables:
        PYLENE_CONFIGURATION: "Release"
        CXX: "g++"
        CC: "gcc"
        BENCKMARK: "True"

distcheck-linux-clang-release:
    <<: *distcheck-linux-base
    variables:
        PYLENE_CONFIGURATION: "Release"
        CXX: "clang++"
        CC: "clang"
        BENCKMARK: "True"

distcheck-linux-gcc-debug:
    <<: *distcheck-linux-base
    variables:
        PYLENE_CONFIGURATION: "Debug"
        CXX: "g++"
        CC: "gcc"
        BENCKMARK: "False"

distcheck-linux-clang-debug:
    <<: *distcheck-linux-base
    variables:
        PYLENE_CONFIGURATION: "Debug"
        CXX: "clang++"
        CC: "clang"
        BENCKMARK: "False"

build-doc-images:
    stage: build
    script:
        - mkdir build && cd build
        - conan remote add $CONAN_PRIVATE_REMOTE_NAME $CONAN_PRIVATE_REMOTE_URL
        - conan user
              -p $CONAN_API_KEY
              -r $CONAN_PRIVATE_REMOTE_NAME $CONAN_USER
        - conan remote list
        - conan install .. --build missing -o benchmark=False
        - cmake ..
        - cmake --build . --config Release --target build-images
    artifacts:
        paths:
            - doc/source/images


#################
# Documentation #
#################

.documentation-base:  &documentation-base
    stage: test
    script:
        - cd doc
        - doxygen
        - sphinx-build -b html source ../public
    artifacts:
        name: "documentation"
        paths:
            - public/

# Generate doc only
documentation:
    <<: *documentation-base
    except:
    - dev

# Deploy
pages:
    <<: *documentation-base
    only:
    - dev
